// AUTO-GENERATED by obsidian-smart-env/build/build_env_config.js. DO NOT EDIT.
import lookup_lists from './src/collections/lookup_lists.js';
import { LookupList } from './src/items/lookup_list.js';

import { render as collection_settings_component } from './src/components/collection_settings.js';
import { render as context_item_leaf_component } from './src/components/context-item/leaf.js';
import { render as env_settings_component } from './src/components/env_settings.js';
import { render as env_stats_component } from './src/components/env_stats.js';
import { render as lean_coffee_callout_component } from './src/components/lean_coffee_callout.js';
import { render as muted_notices_component } from './src/components/muted_notices.js';
import { render as notifications_feed_component } from './src/components/notifications_feed.js';
import { render as settings_embeddings_component } from './src/components/settings/embeddings.js';
import { render as settings_smart_env_component } from './src/components/settings/smart_env.js';
import { render as settings_source_exclusions_component } from './src/components/settings/source_exclusions.js';
import { render as smart_context_actions_component } from './src/components/smart-context/actions.js';
import { render as smart_context_item_component } from './src/components/smart-context/item.js';
import { render as smart_context_meta_component } from './src/components/smart-context/meta.js';
import { render as smart_context_tree_component } from './src/components/smart-context/tree.js';
import { render as smart_plugins_component } from './src/components/smart_plugins.js';
import { render as source_inspector_component } from './src/components/source_inspector.js';
import { render as status_bar_component } from './src/components/status_bar.js';
import { render as supporter_callout_component } from './src/components/supporter_callout.js';
import { render as user_agreement_callout_component } from './src/components/user_agreement_callout.js';
import { copy_to_clipboard as context_copy_to_clipboard_action } from './src/actions/context/copy_to_clipboard.js';
import { merge_template as context_item_merge_template_action, settings_config as context_item_merge_template_action_settings_config, default_settings as context_item_merge_template_action_default_settings } from './src/actions/context-item/merge_template.js';
import { merge_template as context_merge_template_action, settings_config as context_merge_template_action_settings_config, default_settings as context_merge_template_action_default_settings } from './src/actions/context/merge_template.js';
import { context_suggest_blocks as context_suggest_blocks_action, display_name as context_suggest_blocks_action_display_name } from './src/actions/context-suggest/blocks.js';
import { context_suggest_sources as context_suggest_sources_action, display_name as context_suggest_sources_action_display_name } from './src/actions/context-suggest/sources.js';
import { pre_process as lookup_list_pre_process_action, pre_process as lookup_list_pre_process_action_pre_process } from './src/actions/lookup-list/pre_process.js';
import { similarity as similarity_action, settings_config as similarity_action_settings_config, display_name as similarity_action_display_name, display_description as similarity_action_display_description } from './src/actions/similarity.js';
import { source_open as source_open_action } from './src/actions/source/open.js';

export const smart_env_config = {
  collections: {
    lookup_lists
  },
  item_types: {
    LookupList
  },
  items: {
    lookup_list: { class: LookupList }
  },
  modules: {

  },
  components: {
    collection_settings: { render: collection_settings_component },
    context_item_leaf: { render: context_item_leaf_component },
    env_settings: { render: env_settings_component },
    env_stats: { render: env_stats_component },
    lean_coffee_callout: { render: lean_coffee_callout_component },
    muted_notices: { render: muted_notices_component },
    notifications_feed: { render: notifications_feed_component },
    settings_embeddings: { render: settings_embeddings_component },
    settings_smart_env: { render: settings_smart_env_component },
    settings_source_exclusions: { render: settings_source_exclusions_component },
    smart_context_actions: { render: smart_context_actions_component },
    smart_context_item: { render: smart_context_item_component },
    smart_context_meta: { render: smart_context_meta_component },
    smart_context_tree: { render: smart_context_tree_component },
    smart_plugins: { render: smart_plugins_component },
    source_inspector: { render: source_inspector_component },
    status_bar: { render: status_bar_component },
    supporter_callout: { render: supporter_callout_component },
    user_agreement_callout: { render: user_agreement_callout_component }
  },
  actions: {
    context_copy_to_clipboard: { action: context_copy_to_clipboard_action },
    context_item_merge_template: { action: context_item_merge_template_action, settings_config: context_item_merge_template_action_settings_config, default_settings: context_item_merge_template_action_default_settings },
    context_merge_template: { action: context_merge_template_action, settings_config: context_merge_template_action_settings_config, default_settings: context_merge_template_action_default_settings },
    context_suggest_blocks: { action: context_suggest_blocks_action, display_name: context_suggest_blocks_action_display_name },
    context_suggest_sources: { action: context_suggest_sources_action, display_name: context_suggest_sources_action_display_name },
    lookup_list_pre_process: { action: lookup_list_pre_process_action, pre_process: lookup_list_pre_process_action_pre_process },
    similarity: { action: similarity_action, settings_config: similarity_action_settings_config, display_name: similarity_action_display_name, display_description: similarity_action_display_description },
    source_open: { action: source_open_action }
  }
};
